"""Add new tables for detailed safety report storage

Revision ID: 0ff050ad4d2e
Revises: 
Create Date: 2025-07-24 17:12:19.532299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff050ad4d2e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harmful_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('categories', sa.Text(), nullable=True),
    sa.Column('verification_source', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transcriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('word_timestamps', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('harmful_event_id', sa.String(), nullable=False),
    sa.Column('transcript_snippet', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['harmful_event_id'], ['harmful_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('harmful_event_id', sa.String(), nullable=False),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['harmful_event_id'], ['harmful_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_labels',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('visual_evidence_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visual_evidence_id'], ['visual_evidence.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('videos', sa.Column('safety_rating', sa.String(length=20), nullable=True))
    op.add_column('videos', sa.Column('harmful_events_count', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('overall_confidence_score', sa.Integer(), nullable=True))
    op.add_column('videos', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'summary')
    op.drop_column('videos', 'overall_confidence_score')
    op.drop_column('videos', 'harmful_events_count')
    op.drop_column('videos', 'safety_rating')
    op.drop_table('image_labels')
    op.drop_table('visual_evidence')
    op.drop_table('audio_evidence')
    op.drop_table('transcriptions')
    op.drop_table('harmful_events')
    # ### end Alembic commands ###
