"""add_v2_columns_to_harmful_events

Revision ID: 2630dbdc9f54
Revises: 9c7bcb937425
Create Date: 2025-09-02 14:32:49.775320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2630dbdc9f54'
down_revision: Union[str, Sequence[str], None] = '9c7bcb937425'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
