"""Update videos table to include analysis_model

Revision ID: 2a36560869f7
Revises: caae70d2f47d
Create Date: 2025-08-07 16:32:55.074028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a36560869f7'
down_revision: Union[str, Sequence[str], None] = 'caae70d2f47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('analysis_model', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'analysis_model')
    # ### end Alembic commands ###
