"""Update accounts table id to not auto generate using uuid

Revision ID: 4a61097f2214
Revises: c0d3cb0d6a6d
Create Date: 2025-08-03 19:33:31.098266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a61097f2214'
down_revision: Union[str, Sequence[str], None] = 'c0d3cb0d6a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
