"""add url download support columns to videos table

Revision ID: 87a9a7d5971e
Revises: 2a36560869f7
Create Date: 2025-08-11 23:39:19.343295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a9a7d5971e'
down_revision: Union[str, Sequence[str], None] = '2a36560869f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('original_url', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('download_provider', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('download_status', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('download_metadata', sa.Text(), nullable=True))
    op.add_column('videos', sa.Column('download_error', sa.Text(), nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE videos SET source_type = 'upload' WHERE source_type IS NULL")
    op.execute("UPDATE videos SET download_status = 'completed' WHERE source_type = 'upload'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'download_error')
    op.drop_column('videos', 'download_metadata')
    op.drop_column('videos', 'download_status')
    op.drop_column('videos', 'download_provider')
    op.drop_column('videos', 'original_url')
    op.drop_column('videos', 'source_type')
    # ### end Alembic commands ###
