"""add_cascade_delete_constraints

Revision ID: 87c8f21debe5
Revises: 0ff050ad4d2e
Create Date: 2025-07-24 20:38:26.402497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87c8f21debe5'
down_revision: Union[str, Sequence[str], None] = '0ff050ad4d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('audio_evidence_harmful_event_id_fkey'), 'audio_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'audio_evidence', 'harmful_events', ['harmful_event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('harmful_events_video_id_fkey'), 'harmful_events', type_='foreignkey')
    op.create_foreign_key(None, 'harmful_events', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('image_labels_visual_evidence_id_fkey'), 'image_labels', type_='foreignkey')
    op.create_foreign_key(None, 'image_labels', 'visual_evidence', ['visual_evidence_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transcriptions_video_id_fkey'), 'transcriptions', type_='foreignkey')
    op.create_foreign_key(None, 'transcriptions', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('videos_account_id_fkey'), 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'accounts', ['account_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('visual_evidence_harmful_event_id_fkey'), 'visual_evidence', type_='foreignkey')
    op.create_foreign_key(None, 'visual_evidence', 'harmful_events', ['harmful_event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visual_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('visual_evidence_harmful_event_id_fkey'), 'visual_evidence', 'harmful_events', ['harmful_event_id'], ['id'])
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key(op.f('videos_account_id_fkey'), 'videos', 'accounts', ['account_id'], ['id'])
    op.drop_constraint(None, 'transcriptions', type_='foreignkey')
    op.create_foreign_key(op.f('transcriptions_video_id_fkey'), 'transcriptions', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'image_labels', type_='foreignkey')
    op.create_foreign_key(op.f('image_labels_visual_evidence_id_fkey'), 'image_labels', 'visual_evidence', ['visual_evidence_id'], ['id'])
    op.drop_constraint(None, 'harmful_events', type_='foreignkey')
    op.create_foreign_key(op.f('harmful_events_video_id_fkey'), 'harmful_events', 'videos', ['video_id'], ['id'])
    op.drop_constraint(None, 'audio_evidence', type_='foreignkey')
    op.create_foreign_key(op.f('audio_evidence_harmful_event_id_fkey'), 'audio_evidence', 'harmful_events', ['harmful_event_id'], ['id'])
    # ### end Alembic commands ###
