"""add_v2_columns_to_harmful_events

Revision ID: 9c7bcb937425
Revises: ebd4d4eb356e
Create Date: 2025-09-02 14:01:13.042398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c7bcb937425'
down_revision: Union[str, Sequence[str], None] = 'ebd4d4eb356e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('harmful_events', sa.Column('start_time', sa.Float(), nullable=True))
    op.add_column('harmful_events', sa.Column('end_time', sa.Float(), nullable=True))
    op.add_column('harmful_events', sa.Column('analysis_performed', sa.Text(), nullable=True))
    op.add_column('harmful_events', sa.Column('planning_mode', sa.String(length=50), nullable=True))
    op.add_column('harmful_events', sa.Column('report_version', sa.Integer(), nullable=True))
    op.add_column('harmful_events', sa.Column('analysis_run_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'harmful_events', 'analysis_runs', ['analysis_run_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'harmful_events', type_='foreignkey')
    op.drop_column('harmful_events', 'analysis_run_id')
    op.drop_column('harmful_events', 'report_version')
    op.drop_column('harmful_events', 'planning_mode')
    op.drop_column('harmful_events', 'analysis_performed')
    op.drop_column('harmful_events', 'end_time')
    op.drop_column('harmful_events', 'start_time')
    # ### end Alembic commands ###
