"""Update accounts table structure for Auth.js

Revision ID: c0d3cb0d6a6d
Revises: 87c8f21debe5
Create Date: 2025-08-03 16:52:53.715733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d3cb0d6a6d'
down_revision: Union[str, Sequence[str], None] = '87c8f21debe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('accounts', sa.Column('image', sa.String(), nullable=True))
    op.drop_index(op.f('ix_accounts_workos_user_id'), table_name='accounts')
    op.drop_column('accounts', 'workos_user_id')
    op.drop_column('accounts', 'last_name')
    op.drop_column('accounts', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('accounts', sa.Column('workos_user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_accounts_workos_user_id'), 'accounts', ['workos_user_id'], unique=True)
    op.drop_column('accounts', 'image')
    op.drop_column('accounts', 'name')
    # ### end Alembic commands ###
