"""Update accounts table id to include session_uuid

Revision ID: caae70d2f47d
Revises: 4a61097f2214
Create Date: 2025-08-03 21:03:09.279740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caae70d2f47d'
down_revision: Union[str, Sequence[str], None] = '4a61097f2214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('session_uuid', sa.String(), nullable=True))
    op.create_index(op.f('ix_accounts_session_uuid'), 'accounts', ['session_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_session_uuid'), table_name='accounts')
    op.drop_column('accounts', 'session_uuid')
    # ### end Alembic commands ###
